### ISSUE TITLE
長音符をどうするか

### ISSUE THREAD

**Issue by hanubeki** [Tiny-Foxes/OutFox-ja#2]
外来語の-er, -or, -ry等において、長音符「ー」を付けるか付けないかで流儀が分かれており、StepManiaの日本語.iniファイルにおいても混在しているのが現状です。
https://ja.wikipedia.org/wiki/%E9%95%B7%E9%9F%B3%E7%AC%A6#%E9%95%B7%E9%9F%B3%E7%AC%A6%E3%82%92%E4%BB%98%E3%81%91%E3%82%8B%E6%B5%81%E5%84%80%E3%83%BB%E4%BB%98%E3%81%91%E3%81%AA%E3%81%84%E6%B5%81%E5%84%80

個人的には伸ばす方を採用したいのですが、他の方はどうなのか意見を聞きたいところです。

**Comment by JapanYoshi** [comment]
伸ばす方に賛成です。Windowsも移行しましたしね。

**Comment by hanubeki** [comment]
他に意見がなければ今月末を目途に長音符を付ける作業を始めたいと思います。

**Comment by hanubeki** [comment]
スコア、クリア、ディレクトリ、セカンダリ以外は長音符を付けました。
（メモリーについてはMicrosoftでは伸ばさないようなので要再検討）

**Comment by hanubeki** [comment]
「メモリー」については「メモリーカード」が伸ばす表記なのでそちらに合わせます。Issue閉じます。
