### ISSUE TITLE
「…」統一

### ISSUE THREAD

**Issue by JapanYoshi** [Tiny-Foxes/OutFox-ja#3]
半角ピリオド3つの表記と、全角3点リーダーの表記が、日本語翻訳で混じっていることに、今日見つけた文字化けバグで気づきました。どちらかに統一したほうがいいと思います。

**Comment by hanubeki** [comment]
そうですね、今週中をめどに対応します。

**Comment by hanubeki** [comment]
他の言語ファイルと同様に半角ピリオド3つに統一しようかと思います。

**Comment by hanubeki** [comment]
a97dbd3afedbd0f55b0166a0a9c1d1423fdf45b0 で対応しました。
